language: java
jdk:
  - openjdk15
addons:
  sonarcloud:
    organization: kobero98
    token: d8a3c895e5635111b05f306ed263796fa9542391
script:
  - ant -buildfile EsameISPW1802/build.xml
  - sonar-scanner